import type { ReactNode } from "react";
import { Box, Button, Chip, Paper, Stack, Typography } from "@mui/material";
import { FileUp, FolderUp, HardDrive, Plus, ShieldCheck } from "lucide-react";

export function DatasetsPage() {
  return <Stack spacing={3.25}>
    <Stack direction={{ xs: "column", sm: "row" }} spacing={2} sx={{ justifyContent: "space-between", alignItems: { sm: "flex-end" } }}><Box><Typography variant="h4">Dữ liệu nguồn</Typography><Typography color="text.secondary" sx={{ mt: .7 }}>Raw asset được version hoá, giữ private và xử lý bất đồng bộ trên hạ tầng nội bộ.</Typography></Box><Stack direction="row" spacing={1.1}><Button variant="outlined" startIcon={<FolderUp size={17} />}>Import nội bộ</Button><Button variant="contained" startIcon={<Plus size={17} />}>Dataset mới</Button></Stack></Stack>
    <Box sx={{ display: "grid", gridTemplateColumns: { lg: ".85fr 1.55fr" }, gap: 2 }}>
      <Paper variant="outlined" sx={{ p: 2.6, borderColor: "#e2e9e7" }}><Stack direction="row" spacing={1.1} sx={{ alignItems: "center" }}><Box sx={{ p: 1, borderRadius: 2, bgcolor: "secondary.light", color: "secondary.dark", display: "grid" }}><HardDrive size={19} /></Box><Box><Typography sx={{ fontWeight: 750 }}>Raw storage</Typography><Typography variant="caption" color="text.secondary">Ceph S3 / raw bucket</Typography></Box></Stack><Box sx={{ mt: 2.5, p: 1.5, borderRadius: 2.5, bgcolor: "#f6f9f8" }}><Typography variant="caption" color="text.secondary">Khi Ceph RGW sẵn sàng, file sẽ được tải lên bằng multipart presigned URL. Browser không truy cập S3 credential.</Typography></Box><Stack spacing={1.15} sx={{ mt: 2.3 }}><Policy icon={<ShieldCheck size={16} />} text="Raw data immutable" /><Policy icon={<FileUp size={16} />} text="Version được audit đầy đủ" /></Stack></Paper>
      <Paper variant="outlined" sx={{ minHeight: 350, display: "grid", placeItems: "center", p: 3, textAlign: "center", borderStyle: "dashed", borderColor: "#cfdcda", bgcolor: "#fbfcfc" }}><Box sx={{ maxWidth: 420 }}><Box sx={{ mx: "auto", width: 66, height: 66, display: "grid", placeItems: "center", borderRadius: 4, bgcolor: "primary.light", color: "primary.main" }}><FolderUp size={30} /></Box><Typography variant="h5" sx={{ mt: 2.25 }}>Chưa có dataset nào</Typography><Typography color="text.secondary" sx={{ mt: .8, lineHeight: 1.65 }}>Bắt đầu bằng một file GeoTIFF, GeoPackage, Shapefile hoặc MBTiles. Hệ thống sẽ lưu raw file trước khi tạo version tileset.</Typography><Stack direction="row" spacing={1} sx={{ mt: 2.5, justifyContent: "center", flexWrap: "wrap", rowGap: 1 }}><Chip label="GeoTIFF" size="small" /><Chip label="GeoPackage" size="small" /><Chip label="MBTiles" size="small" /><Chip label="Shapefile" size="small" /></Stack><Button variant="contained" startIcon={<Plus size={17} />} sx={{ mt: 2.7 }}>Tạo dataset đầu tiên</Button></Box></Paper>
    </Box>
  </Stack>;
}

function Policy({ icon, text }: { icon: ReactNode; text: string }) { return <Stack direction="row" spacing={.8} sx={{ alignItems: "center", color: "text.secondary" }}><Box sx={{ color: "secondary.main", display: "grid" }}>{icon}</Box><Typography variant="caption">{text}</Typography></Stack>; }
